### ISSUE TITLE
What if  ;; isFalse();

### ISSUE THREAD

**Issue by Krip9Gamer** [Cqdet/isTrue#1]

**Comment by Cqdet** [comment]
Complete blasphemy,`isTrue` is strictly for determining if a boolean value is **TRUE** not **FALSE**. Offended by this issue, closing it immediately.

**Comment by Krip9Gamer** [comment]
Theoretically isTrue isn't stated as a "protected" boolean so?

**Comment by Cqdet** [comment]
WDYM - This isn't a class, there is no need for a `protected` modifier
